### ISSUE TITLE
Website non-functional

### ISSUE THREAD

**Issue by psharma04** [MoltenCoffee/space-haven-editor#1]
## Expected Behaviour
Space Haven save editor interface should appear in the browser window when navigating to [https://spacehaven-editor.com](https://spacehaven-editor.com).

## Encountered Behaviour
Blank page with dark blue background and the title "Space Haven Editor" in the browser's default font. Error messages regarding React in browser log (see attached).

## Environment
Opera Version 82.0.4227.33, Firefox 96.0, Safari Version 15.3 (17612.4.2.1.2) all displayed this behaviour.

## Log Files
[spacehaven-editor.com-1642038815364.log](https://github.com/MoltenCoffee/space-haven-editor/files/7859221/spacehaven-editor.com-1642038815364.log)

**Comment by MoltenCoffee** [comment]
Thanks! I haven't been able to work on this for some time, although I did blindly update some dependencies.. oops.
It should be working again now!

The editor hasn't been tested for the newest game versions, I'll work on that in the near future. Should you find any incompatibilities, I'd be happy to hear them!
